CREATE TABLE `diaria` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `bairro` varchar(30) NOT NULL,
  `cep` varchar(8) NOT NULL,
  `cidade` varchar(30) NOT NULL,
  `codigo_ibge` varchar(255) NOT NULL,
  `complemento` varchar(100) DEFAULT NULL,
  `data_atendimento` datetime(6) NOT NULL,
  `estado` varchar(2) NOT NULL,
  `logradouro` varchar(60) NOT NULL,
  `motivo_cancelamento` varchar(255) DEFAULT NULL,
  `numero` varchar(10) NOT NULL,
  `observacoes` varchar(255) DEFAULT NULL,
  `quantidade_banheiros` int NOT NULL,
  `quantidade_cozinhas` int NOT NULL,
  `quantidade_outros` int NOT NULL,
  `quantidade_quintais` int NOT NULL,
  `quantidade_quartos` int NOT NULL,
  `quantidade_salas` int NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'SEM_PAGAMENTO',
  `tempo_atendimento` int NOT NULL,
  `valor_comissao` decimal(19,2) NOT NULL,
  `preco` decimal(19,2) NOT NULL,
  `cliente_id` bigint NOT NULL,
  `diarista_id` bigint DEFAULT NULL,
  `servico_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`servico_id`) REFERENCES `servico` (`id`),
  FOREIGN KEY (`diarista_id`) REFERENCES `usuario` (`id`),
  FOREIGN KEY (`cliente_id`) REFERENCES `usuario` (`id`)
);
